# Generated by Django 4.2.3 on 2023-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecords',
            name='email',
            field=models.EmailField(default='vasu@gmai.com', max_length=254),
        ),
    ]
