# Generated by Django 4.2.3 on 2023-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessrecords_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecords',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='TopicName',
            new_name='Topic_name',
        ),
        migrations.RenameField(
            model_name='webpage',
            old_name='TopicName',
            new_name='Topic_name',
        ),
        migrations.AlterField(
            model_name='accessrecords',
            name='email',
            field=models.EmailField(default='vasu@gmail.com', max_length=254),
        ),
    ]
